#include "shaderlib/cshader.h"
class depthtodestalpha_ps40_Static_Index
{
public:
	depthtodestalpha_ps40_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_depthtodestalpha_ps40 0
class depthtodestalpha_ps40_Dynamic_Index
{
public:
	depthtodestalpha_ps40_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_depthtodestalpha_ps40 0
